### ISSUE TITLE
Microsoft AD Integration

### ISSUE THREAD

**Issue by chitralverma** [bitnami/bitnami-docker-openldap#13]
This issue is regarding the question, can I use this with Microsoft AD as my identity provider. If yes, then how ?

**Comment by dani8art** [comment]
Hi @chitralverma could you elaborate a bit more on your use case, please? Are you using [Azure Active Directory](https://azure.microsoft.com/en-gb/services/active-directory/) or an on-premise version?

In principle, I think you should be able to use it since AD support LDAP and OpenLDAP is an open-source implementation. I can find some tutorial that could help you to configure:
- https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/auth-ldap
- https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-configure-ldaps 

Thanks!

**Comment by rafariossaa** [comment]
Hi @chitralverma ,
  I think @dani8art links are a starting point, but I'd suggest you also to ask in openldap forums where you could get a better answer of the details of that kind of usage. AD speaks LDAP protocol but I am not sure if the implementation would work for you.
