### ISSUE TITLE
please document `$BITNAMI_DEBUG`

### ISSUE THREAD

**Issue by klaernie** [bitnami/bitnami-docker-openldap#36]
Hello there,

this doesn't really fit the regular bug reports, as it's only in the README.

Could you please document the `$BITNAMI_DEBUG` environment variable in the image?
I had a problem where loading a custom schema failed, and so the container just stopped - without even a message. After 30 minutes of head scratching I dug through the code to see where it precisely failed, and noticed the `debug_execute` function. After setting it to `true` I found my mistake immediately.

Best regards,
Andre

**Comment by carrodher** [comment]
Hi, what do you mean by documenting the environment variable in the image? As the bash code of this image is available in this repository maybe you would like to create a PR with the idea you have in mind so we can review it, add our opinion, and merge the changes.
In the same way it is something applicable to all the Bitnami container images so we can work after that in order to apply the suggestion in the whole catalogue, but I would like to see an example of your proposal.

**Comment by heinebold** [comment]
Hadn't google led me to this issue, I'd be still searching. Made a PR.

**Comment by carrodher** [comment]
We will wait for the PR to see what is your proposal and determine if it can be applied to the whole catalog. Thanks!
