### ISSUE TITLE
Unable to run as root

### ISSUE THREAD

**Issue by yinheli** [bitnami/bitnami-docker-openldap#73]
**Description**

**Steps to reproduce the issue:**

```
docker run --rm -it -u root \
 -e LDAP_ROOT=dc=example,dc=com \
 -e LDAP_ADMIN_USERNAME=admin \
 -e LDAP_ADMIN_PASSWORD=8190ca58efdd51ed \
 -e LDAP_DAEMON_USER=root \
 -e LDAP_DAEMON_GROUP=root \
 -e BITNAMI_DEBUG=true \
 bitnami/openldap:2.6.0 
```

**Describe the results you received:**

```
 09:13:26.73 INFO  ==> ** Starting LDAP setup **
 09:13:26.83 INFO  ==> Validating settings in LDAP_* env vars
 09:13:26.92 INFO  ==> Initializing OpenLDAP...
 09:13:26.93 DEBUG ==> Ensuring expected directories/files exist...
 09:13:26.97 INFO  ==> Creating LDAP online configuration
Closing DB...
 09:13:27.00 INFO  ==> Starting OpenLDAP server in background
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

**Comment by alemorcuq** [comment]
Hi, @yinheli.

Thanks for reporting this. I've been able to reproduce your issue: the container doesn't start when running as root. However, it works properly when launched as a non-root user. Given that, it's not a priority for us to try and fix this now.

Nevertheless, since the code is published in this repository, we would gladly review a PR should you (or someone else) decide to contribute.
