### ISSUE TITLE
ldap_start_tls: Can't contact LDAP server (-1)

### ISSUE THREAD

**Issue by fiftin** [bitnami/bitnami-docker-openldap#78]
I started the LDAP server with `LDAP_ENABLE_TLS=yes`. I provided correct certificates. Server works.

But when I try connect to the server, client returns error:

```
ldap_start_tls: Can't contact LDAP server (-1)
        additional info: The TLS connection was non-properly terminated.
```

I tried different client settings, but results the same. I tried connect via Golang, same result.

Server logs:

```
conn=1001 fd=14 ACCEPT from IP=172.30.0.1:33326 (IP=0.0.0.0:1636)
TLS: init_def_ctx: .
conn=1001 fd=14 closed (TLS negotiation failure)
```

Without TLS all works fine.

**Comment by miguelaeh** [comment]
Hi @fiftin ,
Could you give it a try with a different client? This sometimes happens when the client/server socket is closed before the connection finishes. It could be due to a client configuration error or to the client itself.
Making some tests with different clients we can check if this is related to the client, its configuration or to the server

**Comment by miguelaeh** [comment]
Hi @kennhung ,
> From the [source code of openldap](https://github.com/openldap/openldap/blob/master/libraries/libldap/tls2.c#L298), it should show the content of errmsg before the `.`.

isn't the error `conn=1001 fd=14 closed (TLS negotiation failure)` ?
