### ISSUE TITLE
CRITICAL - Incorrect URI usage

### ISSUE THREAD

**Issue by helvetia007** [bitnami/bitnami-docker-openldap#80]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

1 minute to reproduce!
Run a default image.
Docker exec inside the image
Use "ps x"

Witness that launch command contains "-h ldap://:1389" . Instead this should have "-h ldap://hostname:1389".
Hostname should be picked up from --hostname docker directive.

Without this, N way replication does not work. Perhaps other things too. It is abnormal to NOT have hostname in ldap URI.
There is no way to configure this with any existing bitnami env vars nor any config file.

### What is the expected behavior?

ps x
should show correct URI which includes hostname

### What do you see instead?

Incorrect URI usage

**Comment by helvetia007** [comment]
Hi. Replication does not support listening only on ldap://:1389/ . Listening to ldap://:1389/ is wrong according to official replication documentation. Having a hostname here is mandatory and currently there is no way to have it there. OpenLDAP cannot be used correctly according to documentation with this current image, therefore I consider it as a bug in the image. It can't be even customised because image is non-root. And root version of this image completely does not work whatsoever - seems like another bug.

**Comment by marcosbc** [comment]
Hi @helvetia007, since this scenario is not something we are currently supporting, we are flagging it as a feature request. As such, I have just created an internal task for working on this.

Unfortunately I'm unable to provide an ETA for when this would be implemented. If you would like to contribute this feature, feel free to send a PR!

**Comment by helvetia007** [comment]
@marcosbc I would say it is a bug. Because without this the OpenLDAP software does not work as designed. Furthermore, it shall not be difficult to fetch container hostname from --hostname docker parameter.
Currently there is no way to set OpenLDAP URI and according to OpenLDAP official documentation it is something what should be accessible and modifiable by the users.

**Comment by carrodher** [comment]
Thanks for reporting this issue. After some time and due to we are a small team and the rest of the priorities we have in our backlog, this task was not prioritized and there are no plans to work on it in the short/mid term.

Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
