### ISSUE TITLE
Consider including Argon2 support

### ISSUE THREAD

**Issue by jar349** [bitnami/bitnami-docker-openldap#99]
### Name and Version

bitnami/openldap:2.6.1

### What is the problem this feature will solve?

The inability to handle/manage Argon2 password hashes.

### What is the feature you are proposing to solve the problem?

compile openldap with:
- `--with-argon2=libargon2`
- `--enable-argon2`

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this. I have created a internal task to study this.
  We will come back as soon as we have new, however, I can not provide an ETA.

**Comment by jar349** [comment]
I would offer a PR to do this for you, but you seem to have a pre-bundled openldap that you download from bitnami so I cannot change the `./configure` flags nor the environment in which openldap is compiled.

From a security perspective, have you considered making that process more open so that users can see how the binaries get built? Or, perhaps you're already doing that just in another repo and I missed it?

**Comment by rafariossaa** [comment]
Hi,
  Those packages are created internally by our CI/CD. That is a thing that we want to change in the future, but right now it is not possible. There are a bunch of internal tools that help in the compilation process and it won't be straight forward for a external user to contribute.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
